name: vola1
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  randomizer: ^0.0.2
  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.7
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  firebase_database: ^6.1.2
  fluttertoast: ^8.0.6
  provider: ^5.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4

flutter_native_splash:
  color: '#dcbbf2'
  image: assets\splash.png
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf
    - family: Dancing_Script
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf


